CREATE TABLE address (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    street      VARCHAR(255) NOT NULL,
    city        VARCHAR(255) NOT NULL,
    state       VARCHAR(255),
    postal_code VARCHAR(50),
    country     VARCHAR(255)
);

ALTER TABLE property ADD COLUMN address_id BIGINT;

-- Backfill one real Address row per existing Property row, per-row (not by
-- joining on the address string) so duplicate address strings can't collide.
DO $$
DECLARE
    prop RECORD;
    new_address_id BIGINT;
BEGIN
    FOR prop IN SELECT id, address FROM property ORDER BY id LOOP
        INSERT INTO address (street, city)
        VALUES (prop.address, 'Unknown')
        RETURNING id INTO new_address_id;

        UPDATE property SET address_id = new_address_id WHERE id = prop.id;
    END LOOP;
END $$;
